import com.ujizin.camposer.controller.takepicture.AndroidTakePictureCommand
import com.ujizin.camposer.controller.camera.CommonCameraController
import com.ujizin.camposer.controller.record.AndroidRecordController

internal typealias AndroidCameraController = CommonCameraController<AndroidRecordController, AndroidTakePictureCommand>
